[palettes.matugen]
base00 = '{{base16.base00.default.hex}}'
base01 = '{{base16.base01.default.hex}}'
base02 = '{{base16.base02.default.hex}}'
base03 = '{{base16.base03.default.hex}}'
base04 = '{{base16.base04.default.hex}}'
base05 = '{{base16.base05.default.hex}}'
base06 = '{{base16.base06.default.hex}}'
base07 = '{{base16.base07.default.hex}}'
base08 = '{{base16.base08.default.hex | lighten: 20}}'
base09 = '{{base16.base09.default.hex | lighten: 20}}'
base0a = '{{base16.base0a.default.hex | lighten: 20}}'
base0b = '{{base16.base0b.default.hex | lighten: 20}}'
base0c = '{{base16.base0c.default.hex | lighten: 20}}'
base0d = '{{base16.base0d.default.hex | lighten: 20}}'
base0e = '{{base16.base0e.default.hex | lighten: 20}}'
base0f = '{{base16.base0f.default.hex | lighten: 20}}'

black = '{{base16.base00.default.hex}}'
bright-black = '{{base16.base03.default.hex}}'
white = '{{base16.base05.default.hex}}'
bright-white = '{{base16.base07.default.hex}}'
red = '{{base16.base08.default.hex | lighten: 20}}'
orange = '{{base16.base09.default.hex | lighten: 20}}'
yellow = '{{base16.base0a.default.hex | lighten: 20}}'
green = '{{base16.base0b.default.hex | lighten: 20}}'
cyan = '{{base16.base0c.default.hex | lighten: 20}}'
blue = '{{base16.base0d.default.hex | lighten: 20}}'
purple = '{{base16.base0e.default.hex | lighten: 20}}'
brown = '{{base16.base0f.default.hex | lighten: 20}}'
