gmail-oauth: ENC[AES256_GCM,data:gUQqzSwcHE3rrzToO+rVIVTtmU0dlarhxLD/j6b9Bz52wsc9dVtFtAZsYMyQkBOMIIAeqB3G/rIxj5BQPZrgBNpwyQDC9I7RdZ2vhKrqG77zZFOsUEJImeUm9UCYHbBaQImEhYtUFyP7ON6mzW4cU0c4wKeuw/c7zLzz7KwZ6YRVGrauj1g444m+p4iv7XaFyvOWNtNW0vgvmkvjeCfqGC0iXnb74mRf4YXbr9+3Nkefy2sgoEYyLqVteh5+rmVUEEYo2gICcs4+ODohnFskduiEFg/BZSxbKJi/gmz6jvjqv/Ytje3ftw4o6Zo5qPDIYhS+T6FPRNri4ufyHgNBoxaVRzdUYUadvC2YWwjnmRMyxpO+xV1FvsRWNjvtC7E4jlZEu20h3Qr05UpgyihsOjUI+tJC69HbBBNX6yCa7p+pN6FbNzvAciutmFeKnNQ7ZApBTBcd3LIVPIIMFB30IGUcgwN1MzJ4zEYLr3dDhIOx0zr3DHV42RlAG2asovXlkTa2zvdZxg2+hdHXL6yEnyppy0ouHQ==,iv:a55aZ/cGLEgvjlYiiVkAHcZQB/N9PswfpghfTYcH7tA=,tag:EwXBibNfXRfhzy7gELugww==,type:str]
private-email: ENC[AES256_GCM,data:uETv6AUvUppAaPaQw+oqoA==,iv:MleT0Vhywbdnw+f/SDpfqRK1DFW9tKwxKhfA1ZDccNs=,tag:WOfD9FeIy2EgPwyK5fOTPQ==,type:str]
dav-passwd: ENC[AES256_GCM,data:ug/pqHuuIpPXuXjZerEMGA==,iv:9Eg+GPAepN2fPYIrsHeOBDGQe7umy39SPWqp9kFWpMk=,tag:WaD+Zf+alBknYXvPtFxWzA==,type:str]
sops:
    age:
        - recipient: age1yy9f2spvzv6fuv9c3x0nln3z7r03922eafenrx7nud9qdkvh042qr0zd76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYzlkZmNwc3BsRHJzMXAy
            UTBMT2RmVTczWC96SGhxVXRib2NpeGo2QW1jCmE4N2JQOStLbmlISEd4UlRPV0xw
            b0t5SmpRa2hUcGxhMEpwQ1k2aEtEV0kKLS0tIEJIVk41ZTZJVmVvT1FZNVFlQ3BB
            OTRVRVFMLzFYbDRjRVBvZnFHYUJwN1UKsotJ3j9rNpqGQtopI0OgYTvCSZRLU3rT
            0eyVgChpjVl6/KlWksFsFDhbgKeVv9nlQWFMHXEiXdYVwLz8tnAhZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-06T11:15:57Z"
    mac: ENC[AES256_GCM,data:AZ/tdBW5UXpO2Dy+eN122vAHR1RTNDSXhRzcWtxnqJWPhpfh8bKzlc9xa08EGyx3pK3dLp+InweN/OfQW1nfb73iOOoGYXydBgk/Z2i86sVGgm5C/wZjd8DeFJhzqbhaKyTRvORK3f6diFxe+sY/wGB7/tj0t0llqPsUKaWSGiE=,iv:CQkVQGCcYaIH+80Elf9Tam4q5zpRkyPK04z9SPMrI2s=,tag:vNY9kDdORqPjtFNHOoARPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
