gmail-oauth: ENC[AES256_GCM,data:gUQqzSwcHE3rrzToO+rVIVTtmU0dlarhxLD/j6b9Bz52wsc9dVtFtAZsYMyQkBOMIIAeqB3G/rIxj5BQPZrgBNpwyQDC9I7RdZ2vhKrqG77zZFOsUEJImeUm9UCYHbBaQImEhYtUFyP7ON6mzW4cU0c4wKeuw/c7zLzz7KwZ6YRVGrauj1g444m+p4iv7XaFyvOWNtNW0vgvmkvjeCfqGC0iXnb74mRf4YXbr9+3Nkefy2sgoEYyLqVteh5+rmVUEEYo2gICcs4+ODohnFskduiEFg/BZSxbKJi/gmz6jvjqv/Ytje3ftw4o6Zo5qPDIYhS+T6FPRNri4ufyHgNBoxaVRzdUYUadvC2YWwjnmRMyxpO+xV1FvsRWNjvtC7E4jlZEu20h3Qr05UpgyihsOjUI+tJC69HbBBNX6yCa7p+pN6FbNzvAciutmFeKnNQ7ZApBTBcd3LIVPIIMFB30IGUcgwN1MzJ4zEYLr3dDhIOx0zr3DHV42RlAG2asovXlkTa2zvdZxg2+hdHXL6yEnyppy0ouHQ==,iv:a55aZ/cGLEgvjlYiiVkAHcZQB/N9PswfpghfTYcH7tA=,tag:EwXBibNfXRfhzy7gELugww==,type:str]
private-email: ENC[AES256_GCM,data:uETv6AUvUppAaPaQw+oqoA==,iv:MleT0Vhywbdnw+f/SDpfqRK1DFW9tKwxKhfA1ZDccNs=,tag:WOfD9FeIy2EgPwyK5fOTPQ==,type:str]
caldav-token: ENC[AES256_GCM,data:qXegqrgsQu+EpsUub4G9+566CegUXSosCUK//x46BHxFeeX9MzQRMkNUc5Ey5fEuM/q5q48uAgI0E+rjJvy/iA==,iv:9dCeVup3OEN45/uHlVgZhaicHyACwFCKF3/BhVn2sJA=,tag:Aa49UXtwI0iCMf+eDVxfXw==,type:str]
carddav-passwd: ENC[AES256_GCM,data:CZEQnlx3jX2+Rec+w9pA4g==,iv:buK8zF5EN/84Uuvq/w43E40hupsZQPtLicOFUO5VxE4=,tag:hMTfkona/RE/WW0MuP3WZA==,type:str]
gemini-token: ENC[AES256_GCM,data:aWAwr7hwBi/jPWQkEuXSXI9V4qsw/5N7GDvvymb2kjBW6a2CJc9P,iv:99xCtUGfp0lRr4llsT97QUhsVzy+lAKjsbhHaFhkSKY=,tag:RWg2Wonkwb7etsfYfHTsqA==,type:str]
sops:
    age:
        - recipient: age1yy9f2spvzv6fuv9c3x0nln3z7r03922eafenrx7nud9qdkvh042qr0zd76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYzlkZmNwc3BsRHJzMXAy
            UTBMT2RmVTczWC96SGhxVXRib2NpeGo2QW1jCmE4N2JQOStLbmlISEd4UlRPV0xw
            b0t5SmpRa2hUcGxhMEpwQ1k2aEtEV0kKLS0tIEJIVk41ZTZJVmVvT1FZNVFlQ3BB
            OTRVRVFMLzFYbDRjRVBvZnFHYUJwN1UKsotJ3j9rNpqGQtopI0OgYTvCSZRLU3rT
            0eyVgChpjVl6/KlWksFsFDhbgKeVv9nlQWFMHXEiXdYVwLz8tnAhZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T14:11:28Z"
    mac: ENC[AES256_GCM,data:dpnKPJYLtbIe37TzBOvA6JVqeNCWakYHZ2VwTPmf+jWCm0m5vD+pMYN08FSsgXRz1A2vAtHFFk4k5AVfogR3EL2ytfE4aQ3YOVXQMz6VOS8H2d4ObON9XT2i7qkGUQbljFmjJSe6haymTXkV5TaMvjI7okpjHC0YTXofuDWH8sg=,iv:i8MzudWfq62ShmTpUGclrAtfxz8jSpFk3QIoNMjK+Do=,tag:TWAs+cZCjLoIJttjXZ6E1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
